version: "3"
services:
  postgres:
    image: postgres:13
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
      # - ./docker/config/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - back
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DATABASE_PGADMIN4_USER}
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - back
    restart: unless-stopped

networks:
  back:
    driver: bridge
