service: serverless-ecommerce

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  - serverless-offline
  - serverless-plugin-typescript 
  - serverless-dotenv-plugin

# only include the Prisma binary required on AWS Lambda while packaging
package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'

functions:
  listProduct:
    handler: src/lambdas/product-handler.list
    events:
      - http:
          path: /product
          method: get
  createProduct:
    handler: src/lambdas/product-handler.create
    events:
      - http:
          path: /product
          method: post

